Repository Ureka-Middle-Team1/moo-mool, pull requests merged in 2025-06, with the labels that each got.

#18 [FEAT] Husky+Commitlint 및 Eslint+Prettier 재설정
  .vscode/settings.json
  commitlint.config.cjs
  package-lock.json
  package.json
Labels: ⚙ Setting, 🔨 Refactor

#23 feat: #16 Kakao Auth 연동
  .gitignore
  package-lock.json
  package.json
  postcss.config.js
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/lib/auth.ts
  src/app/login/page.tsx
  src/app/login/userinfo/page.tsx
Labels: 🚀 Deploy

#20 [FEAT] Next.js 프로젝트 내부에서 스타일링을 위한 Tailwind v4.1 초기 세팅
  .gitignore
  .prettierrc.json
  .vscode/settings.json
  package.json
  postcss.config.js
  postcss.config.mjs
  src/app/globals.css
  src/app/page.tsx
Labels: ⚙ Setting, 🎨 UI Design

#58 [FEAT] STT & TTS 기능 구현 및 문어 캐릭터 애니메이션 연동
  package.json
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  src/components/chat/CharacterModel.tsx
  src/components/chat/CharacterScene.tsx
  src/components/chat/ShadowRing.tsx
  src/components/chat/VoiceFooter.tsx
  src/hooks/useTTS.ts
  src/hooks/useVoiceRecorder.ts
Labels: ✨ Feature

#57 [FEAT] 밈테스트 홈, 결과 페이지 UI 구현
  public/assets/icons/books-moono.png
  public/assets/icons/calling-moono.png
  public/assets/icons/chat-moono.png
  public/assets/icons/saving-moono.png
  public/assets/icons/sns-moono.png
  public/assets/icons/youtube-moono.png
  public/assets/moono/meme-test-home.png
  src/app/api/test/get-type-rank/route.ts
  src/app/fonts.css
  src/app/globals.css
  src/app/layout.tsx
  src/app/meme-test/page.tsx
  src/app/meme-test/result/page.tsx
  src/components/chart/TrendBar.tsx
  src/components/common/LayoutWrapper.tsx
  src/components/meme/shareSection.tsx
  src/components/plan/planCard.tsx
  src/data/mockPlans.ts
  src/hooks/useGetRecommendedPlanQuery.tsx
  src/hooks/useGetTypeRankQuery.tsx
  src/utils/textUtils.tsx
Labels: 🎨 UI Design

#66 [FEAT] 요금제 추천 결과 파싱 및 카드 형태로 챗봇 응답 처리
  public/assets/moono/chatbot-moono.png
  src/app/chat/TextPage.tsx
  src/app/globals.css
  src/components/chat/ChatInputBox.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatMessageList.tsx
  src/components/chat/PlanCard.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/hooks/useRecommendationPlan.ts
  src/hooks/useWatchRecommendationTrigger.ts
  src/types/Chat.ts
  src/types/Message.ts
Labels: 🎨 UI Design

#72 [FEAT] 요금제 상세페이지 전체 기능 통합 구현
  components.json
  package.json
  public/netflix.jpg
  public/watcha.jpg
  public/youtubePremium.png
  src/app/api/tendency/[id]/route.ts
  src/app/api/tendency/route.ts
  src/app/globals.css
  src/app/providers.tsx
  src/app/tendency/[id]/page.tsx
  src/app/tendency/page.tsx
  src/components/benefit/BenefitCard.tsx
  src/components/chart/TendencyBarChart.tsx
  src/components/chart/TendencyRadarChart.tsx
  src/components/common/TagBadge.tsx
  src/components/planDetail/PlanModeToggle.tsx
  src/components/ui/button.tsx
  src/lib/utils.ts
Labels: 🐞 BugFix

#94 [FEAT] 밈테스트 정보를 통해 Smart Choice API request body 만들어 내는 로직 제작 및 Hook 추가
  src/app/api/chatbot-plan/route.ts
  src/app/api/meme-test/userprofile/route.ts
  src/app/api/smartchoice/route.ts
  src/hooks/useFetchUserMemeTestResult.ts
  src/hooks/useGetFinalPlanInChatbot.ts
  src/hooks/useGetRecommendedPlanQuery.ts
  src/hooks/useRecommendationPlan.ts
  src/hooks/useSmartChoiceRecommendation.ts
  src/hooks/useWatchRecommendationTrigger.ts
  src/lib/chat/queryBySubscribe.ts
  src/lib/chat/selectPlanStrategy.ts
  src/lib/recommend/calculateSmartChoiceValues.ts
  src/types/CalculateInMemeTest.ts
  src/types/Chat.ts
  src/types/plan.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#109 [FEAT] 밈테스트 결과화면 UI + api연동
  public/assets/icons/U_plus.png
  public/assets/icons/arrow.png
  public/assets/icons/moomool_banner.png
  public/assets/icons/stamp_area.png
  public/fonts/BMKkubulimTTF.ttf
  src/app/api/meme-test/ranklists/route.ts
  src/app/fonts.css
  src/app/meme-test/[id]/page.tsx
  src/app/meme-test/page.tsx
  src/app/meme-test/result/[id]/page.tsx
  src/components/meme/shareSection.tsx
  src/hooks/useWebShare.ts
  src/store/memeTypeData.ts
  tailwind.config.js
Labels: ✨ Feature, 📬 API

#106 [FEAT] 구독 요금제 포함한 추천 로직 DB와 연동
  src/app/api/chatbot-plan/route.ts
  src/app/api/meme-test/userprofile/route.ts
  src/app/api/smartchoice/route.ts
  src/app/chat/page.tsx
  src/hooks/useFetchUserMemeTestResult.ts
  src/hooks/useSmartChoiceRecommendation.ts
  src/lib/chat/chatBotQuestionFlow.ts
  src/lib/chat/queryBySubscribe.ts
  src/lib/memeTestRecommend/calculateSmartChoiceValues.ts
  src/store/useTendencyStore.ts
  src/types/CalculateInMemeTest.ts
  src/types/Chat.ts
Labels: ✨ Feature, 📬 API

#132 [FEAT] 카카오톡 공유 기능 구현 및 invited_count / tested_count 증가 로직 추가
  src/app/api/user/invited-count/route.ts
  src/app/meme-test/result/[id]/page.tsx
  src/components/meme/shareSection.tsx
  src/hooks/useGetTypeRankQuery.ts
  src/hooks/useIncreseInvitedCount.ts
  src/hooks/useUpdateTestedCount.ts
Labels: ✨ Feature, 📬 API

#135 [FIX] 배포 ver1.0을 위한 수정 동기화
  .gitignore
  next.config.js
  next.config.ts
  package-lock.json
  package.json
  prisma/seed.ts
  src/app/(swagger)/layout.tsx
  src/app/(swagger)/swagger/SwaggerPage.tsx
  src/app/(swagger)/swagger/page.tsx
  src/app/chat/ChatbotPage.tsx
  src/app/chat/TextPage.tsx
  src/app/chat/VoicePage.tsx
  src/app/chat/page.tsx
  src/app/lib/swagger.ts
  src/hooks/useGetRecommendedPlanQuery.ts
  tsconfig.json
  vercel.json
Labels: 🐞 BugFix

#143 [FIX] 챗봇 입력창 마이크 버튼 클릭 시 음성 모드 전환 & 요금제 카드 클릭 시 상세 페이지 이동 기능 추가
  src/components/chat/ChatInputBox.tsx
  src/components/chat/PlanCard.tsx
Labels: ✨ Feature

#150 [FIX] 밈테스트 로딩 오류 수정 (이미지, 결과 불러오기 오류)
  src/app/meme-test/[id]/page.tsx
  src/app/meme-test/result/[id]/page.tsx
  src/components/meme/QuestionExample.tsx
  src/components/meme/SuspenseImage.tsx
  src/components/ui/spinner.tsx
Labels: 🐞 BugFix

#152 [REFACTOR] 챗봇 멘트 수정 & 자연스러운 대화 관련 내용/프롬프트 추가
  src/app/api/chat-freetalk-summary/route.ts
  src/app/api/chat-freetalk/route.ts
  src/app/chat/TextPage.tsx
  src/hooks/useFreeTalkSummary.ts
  src/hooks/useNormalizeAnswerFlow.ts
  src/hooks/useSmartChoiceRecommendation.ts
  src/hooks/useWatchRecommendationTrigger.ts
  src/lib/chat/callGPTFreeTalk.ts
  src/lib/chat/chatBotQuestionFlow.ts
  src/lib/chat/extractJson.ts
  src/lib/chat/getNextQuestionId.ts
  src/lib/chat/handleFreeTalkAnswer.ts
  src/lib/chat/mapTendencyData.ts
  src/lib/chat/prompts/free_talk.txt
  src/lib/chat/prompts/free_talk_summary.txt
  src/lib/chat/prompts/question_0.txt
  src/lib/chat/prompts/question_11.txt
  src/lib/chat/prompts/question_12.txt
  src/lib/chat/requestFreeTalkSummary.ts
  src/store/useChatStore.ts
  src/store/useFreeTalkStore.ts
  src/types/smartChoiceApiInput.ts
Labels: ✨ Feature, 🐞 BugFix

#164 #153 refactor: DB 재구성 및 툴팁 개선
  src/components/chart/PlanDetailBarChart.tsx
  src/components/chart/options/barChartOptions.ts
  src/components/planDetail/PlanCharts.tsx
  src/types/planDetail.ts
  src/utils/mapPlanToDetailData.ts
Labels: 🔨 Refactor, 🎨 UI Design

#169 [FEAT] 밈테스트 문제 예시 적용, 이미지 조정 과정 추가 및 UI 수정
  public/assets/meme/sns/sns_high_1.svg
  public/assets/meme/sns/sns_low_1.svg
  public/assets/meme/sns/sns_medium_1.svg
  public/assets/meme/youtube/youtube_high_1.svg
  public/assets/meme/youtube/youtube_low_1.svg
  public/assets/meme/youtube/youtube_medium_1.svg
  src/app/globals.css
  src/app/meme-test/[id]/page.tsx
  src/components/meme/ChoiceList.tsx
  src/components/meme/ProgressBar.tsx
  src/components/meme/QuestionExample.tsx
  src/components/meme/QuestionNumber.tsx
  src/components/meme/StageInfo.tsx
  src/components/meme/SuspenseImage.tsx
Labels: ✨ Feature, 🎨 UI Design

#172 [FEAT] 랜딩페이지 구현
  src/app/onboarding/page.tsx
  src/app/page.tsx
  src/components/ui/button.tsx
Labels: ✨ Feature, 🎨 UI Design

#178 [BUG] 시크릿모드 및 공유 링크에서 밈테스트 시작 시 404 오류 발생 문제 해결
  src/app/meme-test/page.tsx
  src/app/meme-test/result/[id]/page.tsx
  src/components/meme/ChoiceList.tsx
  src/components/meme/Header.tsx
Labels: 🐞 BugFix

#203 [DEPLOY] v2.8 카카오톡 미리보기 메타데이터 해
  src/app/meme-test/TestHomePage.tsx
  src/app/meme-test/page.tsx
  src/app/meme-test/rank/page.tsx
  src/app/meme-test/result/[id]/metadata.tsx
  src/app/meme-test/result/[id]/page.tsx
  src/utils/generateMemeMetadata.ts
Labels: 🚀 Deploy

#206 [FEAT] 음성 챗봇 추천 결과시 멘트 message 처리
  src/components/chat/CharacterScene.tsx
Labels: ✨ Feature

#208 [FEAT] 무한스크롤 기능 개선
  src/app/api/plan/page/route.ts
  src/app/plan/page.tsx
  src/components/planList/PlanListTrigger.tsx
  src/hooks/useInfinitePlans.ts
Labels: ✨ Feature, 🐞 BugFix

#217 [FEAT] 챗봇 이전 대화내역 불러오기 기능 구현
  src/app/home/page.tsx
  src/components/common/LayoutWrapper.tsx
  src/components/home/ChatHistoryList.tsx
Labels: ✨ Feature

#215 [FEAT] 배경 및 로고 추가
  src/app/plan/page.tsx
Labels: 🎨 UI Design

#211 [FEAT] home, root와 온보딩 화면 연결 및 신규가입자 확인 API 구현
  src/app/api/auth/is-new-user/route.ts
  src/app/check-user-type/page.tsx
  src/app/onboarding/page.tsx
  src/app/page.tsx
  src/components/home/HomeHeader.tsx
Labels: ✨ Feature, 📬 API

#209 [FEAT] 챗봇 대화내역 요약 기능 및 기존 프롬프트 리팩토링
  src/app/api/chat-freetalk/route.ts
  src/app/api/chat-session/route.ts
  src/app/api/chat-summary/route.ts
  src/app/chat/ChatbotPage.tsx
  src/app/meme-test/result/[id]/resultPage.tsx
  src/components/chat/ChatbotHeader.tsx
  src/hooks/useFreeTalkSummary.ts
  src/hooks/useGetSixTypeRecommendPlan.ts
  src/hooks/usePostChatSession.ts
  src/hooks/usePostChatbotSummary.ts
  src/hooks/useWatchRecommendationTrigger.ts
  src/lib/chat/callGPTFreeTalk.ts
  src/lib/chat/chatBotQuestionFlow.ts
  src/lib/chat/prompts/chatbot_result_summary.txt
  src/lib/chat/prompts/free_talk.txt
  src/lib/chat/prompts/free_talk_summary.txt
  src/lib/chat/prompts/question_0.txt
  src/lib/chat/prompts/question_11.txt
  src/lib/chat/prompts/question_4.txt
  src/lib/chat/prompts/question_9.txt
  src/store/useTendencyStore.ts
Labels: ✨ Feature, 🔨 Refactor

#220 [FIX] 밈테스트-결과페이지 초대 도장 디자인 누락 수정
  src/app/meme-test/result/[id]/resultPage.tsx
Labels: 🐞 BugFix, 🎨 UI Design

#225 [FEAAT] 챗봇 질문 단계에 따른 로드맵 구현
  src/app/chat/TextPage.tsx
  src/components/chat/ChatProgressRoadmap.tsx
  src/components/chat/ChatbotHeader.tsx
Labels: ✨ Feature

#226 [FEAT] 마이페이지-공유 카운트 별 도장 애니메이션 추가 + invited_count zustand 추가
  src/components/myPage/MyPageModal.tsx
  src/components/myPage/UserStamp.tsx
  src/store/userStore.ts
Labels: ✨ Feature, 🎨 UI Design

#228 [FEAT] ChatSession DB 컬럼 추가(plan_id) 및 홈 화면의 카드에 데이터 연동, quickReplyMap 일부 수정
  package.json
  prisma/schema.prisma
  src/app/api/chat-session/route.ts
  src/app/chat/TextPage.tsx
  src/app/chat/[id]/page.tsx
  src/components/chat/ChatInputBox.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatbotHeader.tsx
  src/components/home/ChatHistoryList.tsx
  src/hooks/useGetChatSession.ts
  src/hooks/useGetRecentChatSessions.ts
  src/hooks/usePostChatSession.ts
  src/hooks/usePostChatbotSummary.ts
  src/lib/chat/prompts/free_talk.txt
  src/lib/chat/quickReplyMap.ts
Labels: ✨ Feature

#232 [FEAT] socket stamp
  public/assets/icons/empty_stamp.png
  src/app/nearby/page.tsx
  src/components/nearby/NearbyUserAvatar.tsx
Labels: ✨ Feature, 📬 API

#233 [FEAT] 마이페이지 - 홈 화면에 있던 타입 방사형 그래프 추가
  src/components/home/UserTendencyRadar.tsx
  src/components/myPage/MyPageModal.tsx
Labels: ✨ Feature, 🎨 UI Design

#229 [FEAT] 로드맵 UI 개선
  src/components/chat/ChatProgressRoadmap.tsx
Labels: 🎨 UI Design

#240 [FEAT] 최근 대화 내역에 현재 진행중인 대화 내역 카드 추가
  package.json
  src/app/api/chat-freetalk-summary/route.ts
  src/components/home/ChatHistoryList.tsx
  src/components/home/NowChatProgressBar.tsx
  src/components/ui/tooltip.tsx
  src/lib/chat/requestFreeTalkSummary.ts
Labels: ✨ Feature, 🔨 Refactor

#241 [FEAT] 요금제 카드 PlanListCard 컴포넌트로 통일 및 구독 서비스 정보 추가
  src/app/meme-test/result/[id]/resultPage.tsx
  src/components/chat/CharacterScene.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/PlanCard.tsx
  src/components/home/HomeRecommendedPlan.tsx
  src/components/home/PopularPlansList.tsx
  src/components/planList/PlanListCard.tsx
  src/lib/chat/dbPlanToParsedPlanWithID.ts
  src/types/Chat.ts
  src/utils/mapPlanToDetailData.ts
  src/utils/planDataConverter.ts
Labels: ✨ Feature

#244 [DEPLOY] ver 3.1
  package.json
  public/assets/stamps/levelup_gray.svg
  public/assets/stamps/levelup_red.svg
  src/app/api/chat-freetalk-summary/route.ts
  src/app/api/user/invite-multiple/route.ts
  src/app/chat/ChatbotPage.tsx
  src/app/home/page.tsx
  src/app/meme-test/TestHomePage.tsx
  src/app/meme-test/result/[id]/resultPage.tsx
  src/app/nearby/page.tsx
  src/app/plan/page.tsx
  src/components/chat/CharacterScene.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatbotHeader.tsx
  src/components/chat/PlanCard.tsx
  src/components/home/ChatHistoryList.tsx
  src/components/home/HomeRecommendedPlan.tsx
  src/components/home/NowChatProgressBar.tsx
  src/components/home/PopularPlansList.tsx
  src/components/myPage/MyPageModal.tsx
  src/components/myPage/PlanChart.tsx
  src/components/myPage/PlanSelect.tsx
  src/components/myPage/TypeLevel.tsx
  src/components/myPage/UserSection.tsx
  src/components/myPage/UserStamp.tsx
  src/components/myPage/UserTendencyRadar.tsx
  src/components/nearby/NearbyHeader.tsx
  src/components/planList/PlanListCard.tsx
  src/components/ui/tooltip.tsx
  src/hooks/useGetMyPlan.ts
  src/hooks/useNearbySocket.ts
  src/hooks/usePostMyPlan.ts
  src/lib/chat/dbPlanToParsedPlanWithID.ts
  src/lib/chat/requestFreeTalkSummary.ts
  src/store/useModalStore.ts
  src/types/Chat.ts
  src/utils/mapPlanToDetailData.ts
  src/utils/planDataConverter.ts
Labels: 🚀 Deploy

#245 [STYLE] chatbot UI refactor
  src/app/chat/ChatbotPage.tsx
  src/components/chat/ChatInputBox.tsx
Labels: 🎨 UI Design

#237 [FEAT] 상세페이지 로그인/비로그인 구분 및 레이더 차트 플립
  src/app/api/plan/list/route.ts
  src/app/api/plan/page/route.ts
  src/app/plandetail/[id]/page.tsx
  src/app/planlist/page.tsx
  src/components/chart/PlanDetailBarChart.tsx
  src/components/chart/PlanDetailRadarChart.tsx
  src/components/common/HamburgerMenu.tsx
  src/components/planDetail/FlipCardChart.tsx
  src/components/planDetail/PlanCharts.tsx
  src/components/planDetail/PlanInfo.tsx
  src/components/planDetail/PlanModeToggle.tsx
  src/components/planDetail/StaticStatsCard.tsx
  src/components/planList/SortFilterPanel.tsx
  src/components/planList/StickySortFilter.tsx
  src/constants/labels.ts
  src/hooks/useInfinitePlans.ts
  src/types/sort.ts
  src/utils/mapPlanToDetailData.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 UI Design

#264 #263 feat: 상세페이지 뱃지 DB 연결
  prisma/schema.prisma
  src/app/api/plan/id/[id]/route.ts
  src/components/planDetail/PlanInfo.tsx
  src/components/planDetail/TagBadge.tsx
  src/constants/badgeColors.ts
  src/hooks/usePostMyPlan.ts
  src/types/PlanData.ts
  src/utils/mapPlanToDetailData.ts
Labels: ✨ Feature

#271 [FEAT] 밈테스트 2차 QA 수정
  src/app/meme-test/TestHomePage.tsx
  src/app/meme-test/result/[id]/resultPage.tsx
Labels: ✨ Feature, 🎨 UI Design

#262 [FEAT] 근거리 통신_home 화면에서 주변에 접속한 사용자 감지하여 토스트 알림
  package.json
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/nearby/NearbyContent.tsx
  src/app/nearby/page.tsx
  src/components/nearby/JoinAlertToast.tsx
  src/components/nearby/use-toast.tsx
  src/hooks/useInviteMultiple.ts
  src/hooks/useNearbySocket.ts
  src/hooks/useNearbyStore.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design

#278 [FIX] 챗봇 "자연스러운 대화" 모드 성능 대폭 향상 및 이외 2차 QA 사항 반영
  src/app/api/chat-freetalk/route.ts
  src/app/api/chat-session/route.ts
  src/app/chat/TextPage.tsx
  src/components/home/ChatHistoryList.tsx
  src/components/home/NowChatProgressBar.tsx
  src/hooks/useChatSubmit.ts
  src/hooks/useGetFinalPlanInChatbot.ts
  src/hooks/useSmartChoiceRecommendation.ts
  src/hooks/useWatchRecommendationTrigger.ts
  src/lib/chat/callGPTFreeTalk.ts
  src/lib/chat/chatBotQuestionFlow.ts
  src/lib/chat/handleFreeTalkAnswer.ts
  src/lib/chat/prompts/free_talk.txt
  src/store/useFreeTalkStore.ts
Labels: ✨ Feature, 🐞 BugFix

#276 [FEAT] 페이지 공통 메타데이터 추가
  public/assets/banner/moomool_meta.png
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/common/ClientLayout.tsx
Labels: ✨ Feature

#275 [FEAT] UI 리팩토링
  package.json
  src/app/chat/ChatbotPage.tsx
  src/app/chat/[id]/page.tsx
  src/app/home/page.tsx
  src/app/loading.tsx
  src/app/meme-test/result/[id]/resultPage.tsx
  src/app/page.tsx
  src/app/plandetail/[id]/page.tsx
  src/app/planlist/page.tsx
  src/components/chat/ChatInputBox.tsx
  src/components/chat/ChatMessage.tsx
  src/components/common/FloatingChatbotButton.tsx
  src/components/common/HamburgerMenu.tsx
  src/components/home/ChatHistoryList.tsx
  src/components/home/ChatSessionCard.tsx
  src/components/home/FeatureBannerCard.tsx
  src/components/home/FeatureBannerSlider.tsx
  src/components/home/HomeRecommendedPlan.tsx
  src/components/home/OngoingChatCard.tsx
  src/components/home/PopularPlansList.tsx
  src/components/planList/PlanListCard.tsx
  src/components/skeleton/ChatHeaderSkeleton.tsx
  src/components/skeleton/ChatHistoryListSkeleton.tsx
  src/components/skeleton/ChatMessageListSkeleton.tsx
  src/components/skeleton/ChatSessionCardSkeleton.tsx
  src/components/skeleton/PlanBenefitsSkeleton.tsx
  src/components/skeleton/PlanChartsSkeleton.tsx
  src/components/skeleton/PlanDetailSkeleton.tsx
  src/components/skeleton/PlanInfoSkeleton.tsx
  src/components/skeleton/PlanListCardSkeleton.tsx
  src/components/ui/skeleton.tsx
Labels: 🔨 Refactor, 🎨 UI Design

#289 [FEAT] 차트 중앙 애니메이션 추가 개선
  src/components/planDetail/FlipCardChart.tsx
Labels: ✨ Feature

#292 [FIX] home에서 nearby toast 안보이는 문제 해결
  src/app/layout.tsx
Labels: 🐞 BugFix

#298 [BUG] 홈 페이지 요금제 카드 혜택 가치 버그 수정
  public/assets/ott/youtubePremium.png
  src/components/home/PopularPlansList.tsx
  src/components/planList/PlanListCard.tsx
  src/components/planList/SortFilterPanel.tsx
  src/constants/labels.ts
Labels: 🐞 BugFix, 🔨 Refactor

#301 [DEPLOY] ver4.1
  public/assets/moono/404-moono.png
  public/assets/ott/youtubePremium.png
  src/app/api/user-character-profile/[userId]/route.ts
  src/app/meme-test/TestHomePage.tsx
  src/app/meme-test/[id]/page.tsx
  src/app/meme-test/rank/page.tsx
  src/app/meme-test/result/[id]/resultPage.tsx
  src/app/nearby/page.tsx
  src/app/page.tsx
  src/components/common/ClientLayout.tsx
  src/components/home/ChatHistoryList.tsx
  src/components/home/PopularPlansList.tsx
  src/components/meme/LoadingScreen.tsx
  src/components/meme/NoResultMessage.tsx
  src/components/meme/StageInfo.tsx
  src/components/myPage/UserTendencyRadar.tsx
  src/components/planList/PlanListCard.tsx
  src/components/planList/SortFilterPanel.tsx
  src/constants/labels.ts
  src/lib/chat/callGPTFreeTalk.ts
  src/lib/chat/prompts/free_talk.txt
Labels: 🚀 Deploy

#310 밈테스트 무너에게 물어봐 무물 홈으로 이동
  src/app/meme-test/result/[id]/resultPage.tsx
  src/app/page.tsx
  src/components/common/ClientLayout.tsx
  src/components/home/FeatureBannerCard.tsx
Labels: 🐞 BugFix

#314 [FEAT] 요금제 이름 truncate 적용
  src/components/planDetail/PlanInfo.tsx
  src/components/planList/PlanListCard.tsx
Labels: ✨ Feature

#319 [FIX] 햄버거 프로필 구역에 유저 레벨 별 이미지 뜨도록 코드 수정
  public/assets/moono/lv2/books-moono.png
  public/assets/moono/lv2/calling-moono.png
  public/assets/moono/lv2/chat-moono.png
  public/assets/moono/lv2/saving-moono.png
  public/assets/moono/lv2/sns-moono.png
  public/assets/moono/lv2/youtube-moono.png
  public/assets/moono/lv3/books-moono.png
  public/assets/moono/lv3/calling-moono.png
  public/assets/moono/lv3/chat-moono.png
  public/assets/moono/lv3/saving-moono.png
  public/assets/moono/lv3/sns-moono.png
  public/assets/moono/lv3/youtube-moono.png
  src/components/common/HamburgerMenu.tsx
Labels: 🐞 BugFix, 🎨 UI Design

#324 [FEAT] 근거리 통신 기능 개선
  src/app/nearby/NearbyContent.tsx
  src/components/nearby/NearbyUserAvatar.tsx
  src/hooks/useUserReady.ts
Labels: ✨ Feature, 🔨 Refactor

#332 [REFACTOR] 성능개선 사항
  src/app/api/chat-summary/route.ts
  src/app/providers.tsx
  src/hooks/useGetChatSession.ts
  src/hooks/useGetPlanById.ts
  src/lib/chat/prompts/getSummaryPrompt.ts
Labels: 📬 API

#334 [FIX] 근거리 통신_에러 최종 해결
  src/app/api/user-character-profile/[userId]/route.ts
  src/app/nearby/NearbyContent.tsx
  src/components/nearby/NearbyUserAvatar.tsx
Labels: 🐞 BugFix

#335 Readme
  README.md
Labels: 📃 Docs
